### ISSUE TITLE
Build failure with servant 0.9

### ISSUE THREAD

**Issue by DanBurton** [cdepillabout/yahoo-finance-api#1]
As seen on the Stackage build server trying to build yahoo-finance-api-0.1.0.0:

```
[4 of 7] Compiling Web.Yahoo.Finance.API.JSON.Internal ( src/Web/Yahoo/Finance/API/JSON/Internal.hs, dist/build/Web/Yahoo/Finance/API/JSON/Internal.o )

src/Web/Yahoo/Finance/API/JSON/Internal.hs:144:20: error:
    • Couldn't match type ‘Servant.Common.Req.ClientM QuoteList’
                     with ‘Manager -> BaseUrl -> ExceptT ServantError IO QuoteList’
      Expected type: [StockSymbol]
                     -> Maybe QueryFormat
                     -> Maybe ViewType
                     -> Manager
                     -> BaseUrl
                     -> ExceptT ServantError IO QuoteList
        Actual type: Servant.Client.Client YahooFinanceJsonApi
    • In the expression: client (Proxy :: Proxy YahooFinanceJsonApi)
      In an equation for ‘getQuoteLowLevel’:
          getQuoteLowLevel = client (Proxy :: Proxy YahooFinanceJsonApi)
```

**Comment by DanBurton** [comment]
Note that I've temporarily disabled this package from the Stackage nightly builds. Kindly make a PR or ping me once you've released a new version that addresses the issue.

**Comment by mchaver** [comment]
https://github.com/cdepillabout/yahoo-finance-api/pull/2

I've made a pull request that fixes some of the issues, but it looks like the API is actually no longer available. There are other APIs, but this package is supporting them currently.

**Comment by cdepillabout** [comment]
@mchaver Thanks for the PR.  I really appreciate it!

@DanBurton like @mchaver says, the Yahoo API that this package was accessing is no longer available, so I don't think it makes much sense to get this package back into stackage until it actually works.

However, once it is actually working, I will send a PR to get it back into stackage.

Thanks!

**Comment by cdepillabout** [comment]
The problem has been fixed, so I created a PR to add it back to stackage (https://github.com/fpco/stackage/pull/1982).

Thanks @DanBurton and @mchaver!
