### ISSUE TITLE
API is no longer available

### ISSUE THREAD

**Issue by mchaver** [cdepillabout/yahoo-finance-api#3]
http://stackoverflow.com/questions/38355075/has-yahoo-finance-web-service-disappeared-api-changed-down-temporarily

It looks like there is a work around if you change the User-Agent to a mobile browser, but it will likely get shut down.

**Comment by mchaver** [comment]
http://meumobi.github.io/stocks%20apis/2016/03/13/get-realtime-stock-quotes-yahoo-finance-api.html

working: 
- Yahoo YQL Finance API
- Yahoo CSV Finance API

broken: 
- Yahoo webservice API

**Comment by cdepillabout** [comment]
@mchaver Thanks for the heads up!

I've been planning on changing this package so it accesses the YQL Finance API.  It should (hopefully) be more robust.

However, I don't know if I'll have to time to work on it in the next couple of weeks, so if you (or anyone else?) particularly wanted to use this package, feel free to send a PR.  I'll merge it in and get it released to stackage (#1).

**Comment by mchaver** [comment]
Sure, I'll try it over the weekend and see if I can get it working. I'll probably set it up to give the same information that it was getting with the webservice, and then mark the webservice as deprecated.

**Comment by cdepillabout** [comment]
Okay great!  If you have any questions or anything feel free to let me know!

**Comment by cdepillabout** [comment]
Closed by #4.

**Comment by elizabethsiegle** [comment]
So Yahoo YQL Finance API and Yahoo CSV Finance API are still working? I get a " Could not find module ‘Web.Yahoo.Finance.YQL’ " error on stack build

**Comment by cdepillabout** [comment]
@elizabethsiegle Could you give a little bit more info about how you're running/using `yahoo-finance-api`?  The example in the README.md seems to still work for me.

**Comment by elizabethsiegle** [comment]
@cdepillabout I'm trying to import it in my haskell file

**Comment by elizabethsiegle** [comment]
@cdepillabout For all the inputs, it says "<no location info>: error:
    Could not find module ‘Web.Yahoo.Finance.YQL’
    It is not a module in the current program, or in any known package."

**Comment by cdepillabout** [comment]
@elizabethsiegle I'm not sure what you mean by "all the inputs".  The [`Web.Yahoo.Finance.YQL`](https://github.com/cdepillabout/yahoo-finance-api/blob/master/src/Web/Yahoo/Finance/YQL.hs) module still exists, so I'm not sure what could be going wrong here.

Could you provide the command line you're using to run `stack`?  Also, the `stack.yml` might be helpful.

**Comment by elizabethsiegle** [comment]
wait imports not inputs. I'm trying to import them in my Main.hs and have tried different variations of stack install Web-Yahoo-Finance-YQL

**Comment by elizabethsiegle** [comment]
wait imports not inputs. I'm trying to import them in my Main.hs and have tried different variations of stack install Web-Yahoo-Finance-YQL and when I do it from the command line it says <no location info>: error:
    Could not find module ‘Network.HTTP.Client.TLS’
    It is not a module in the current program, or in any known package.
stack.yaml:
flags: {}
packages:
- '.'
- location:
extra-deps: [attoparsec-iso8601-1.0.0.0, http-api-data-0.3.7, natural-transformation-0.4]
resolver: lts-8.11

**Comment by elizabethsiegle** [comment]
wait imports not inputs. I'm trying to import them in my Main.hs and have tried different variations of stack install Web-Yahoo-Finance-YQL and when I do it from the command line it says : error:
Could not find module ‘Network.HTTP.Client.TLS’
It is not a module in the current program, or in any known package.
stack.yaml:
flags: {}
packages:
- '.'
extra-deps: [attoparsec-iso8601-1.0.0.0, http-api-data-0.3.7, natural-transformation-0.4]
resolver: lts-8.11

**Comment by cdepillabout** [comment]
@elizabethsiegle `yahoo-finance-api` is in stackage:

https://www.stackage.org/lts-8.11/package/yahoo-finance-api-0.2.0.1

So as long as you're using `stack`, you should be good to go.

The module `Network.HTTP.Client.TLS` is from the `http-client-tls` package.  You'll have to add that to your `.cabal` file as well, or specify it on the command line to `stack`.

**Comment by Harrymon12** [comment]
Yahoo finance API is not available anymore. I have moved to MarketXLS after this change, much more reliable data.

**Comment by cdepillabout** [comment]
@Harrymon12 The Yahoo webservice API is not available anymore, but as far as I can tell the Yahoo YQL Finance API is still available.

This package is now using the Yahoo YQL Finance API.  (However, old versions of this package used the Yahoo webservice API.)
